### ISSUE TITLE
New Dawn breaks this

### ISSUE THREAD

**Issue by raddad772** [eliemichel/glfw3webgpu#10]
Trying to compile an ImGUI app. With latest Imgui and Dawn.

.../dev/jsmooch-emus/jsmooch-gui/vendor/glfw3webgpu/glfw3webgpu.c:115:38: error: use of undeclared identifier 'WGPUSType_SurfaceDescriptorFromMetalLayer'; did you mean 'WGPUSType_SurfaceSourceMetalLayer'?
  115 |         fromMetalLayer.chain.sType = WGPUSType_SurfaceDescriptorFromMetalLayer;
      |                                      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                                      WGPUSType_SurfaceSourceMetalLayer
.../dev/jsmooch-emus/cmake-build-jsmooch-gui/_deps/dawn-build/gen/include/dawn/webgpu.h:661:5: note: 'WGPUSType_SurfaceSourceMetalLayer' declared here
  661 |     WGPUSType_SurfaceSourceMetalLayer = 0x00000004,

**Comment by eliemichel** [comment]
Fixed by #9
