### ISSUE TITLE
Merge Emscripten glfw surface logic into glfw3webgpu

### ISSUE THREAD

**Issue by harveynw** [eliemichel/glfw3webgpu#2]
Following the excellent tutorial series, in particular the Emscripten build walk-through:

[Building for the web](https://eliemichel.github.io/LearnWebGPU/appendices/building-for-the-web.html)

It appears the branch for this specific step has its own version of `glfw3webgpu` which has logic [(here)](https://github.com/eliemichel/LearnWebGPU-Code/blob/7f0c61c9e3f564a7b131a5de9c0466f84c6d6cfd/glfw3webgpu/glfw3webgpu.c#L41) for getting a WGPUSurface when compiling with Emscripten. This extra code appears to be missing from this repository's `glfw3webgpu.c`.

When following the steps, with a setup that pulls the dependency from this repository, I naturally get an error at build time:

```
[  8%] Building C object _deps/glfw3webgpu-build/CMakeFiles/glfw3webgpu.dir/glfw3webgpu.c.o
/Users/.../build-web/_deps/glfw3webgpu-src/glfw3webgpu.c:65:10: fatal error: 'GLFW/glfw3native.h' file not found
   65 | #include <GLFW/glfw3native.h>
      |          ^~~~~~~~~~~~~~~~~~~~
1 error generated.
```

This issue is essentially just an ask to get this newer code merged into here for consistency!

Many thanks.

**Comment by eliemichel** [comment]
Yes indeed I must merge this thanks for reminding me! :)

**Comment by eliemichel** [comment]
Oh the change was already in my working copy, just forgot to commit it, now done!
