### ISSUE TITLE
Runtime platform selection support

### ISSUE THREAD

**Issue by Sahnvour** [eliemichel/glfw3webgpu#7]
Since 3.4, GLFW has [runtime platform selection support](https://www.glfw.org/docs/latest/intro_guide.html#platform).
It would be great if your library (and later, upstream change) took care of this to allow runtime choice between xorg or wayland.

**Comment by eliemichel** [comment]
Very good suggestion thanks! Could you tell me whether #8 works for you?

**Comment by Sahnvour** [comment]
I'll try it and get you posted as soon as possible :slightly_smiling_face: thanks

**Comment by Sahnvour** [comment]
Unfortunately I don't have access to a machine that has both X11 and Wayland.

**Comment by eliemichel** [comment]
I tested on a linux VM with both x11 and wayland, somebody checked on macOS, so I guess it's fine, I'll merge the PR!
